theme: jekyll-theme-hacker
title: Manny DaSilva
description: Computer Science student at Southern New Hampshire University, Software Engineer at Rite Solutions Inc.
url: "https://mannydasilvasnhu.github.io"
baseurl: ""