theme: jekyll-theme-hacker
title: Manny DaSilva | Computer Science ePortfolio
description: Security+ Certified Software Engineer at Arcfield | Computer Science Graduate from Southern New Hampshire University | Master's Student in Artificial Intelligence | Focused on secure, scalable, high-performance software development.
url: "https://mannydasilvasnhu.github.io"
baseurl: ""