theme: jekyll-theme-hacker
title: Manny DaSilva | Computer Science ePortfolio
description: Security+ Certified Software Engineer at Arcfield | Computer Science graduate from Southern New Hampshire University | Master's candidate in Computer Science (Artificial Intelligence) | Focused on secure, scalable, and high-performance software development.
url: "https://mannydasilvasnhu.github.io"
baseurl: ""